### ISSUE TITLE
Not working for economist - podcasts

### ISSUE THREAD

**Issue by Rob-li** [bpc-clone/bpc_firefox_support#10]
Describe issue/request: selected economist article still blocked

Link of paywalled article: https://www.economist.com/podcasts/2024/04/30/why-the-one-child-policy-still-affects-chinas-birth-rate

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, reader view

Browser (main version): Safari mobile, firefox125.03

BPC-extension version (number): 3.6.60

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Economist podcasts fixed in latest master (or next release).
