### ISSUE TITLE
Request: manager-magazin.de (Germany)

### ISSUE THREAD

**Issue by realResi** [bpc-clone/bpc_firefox_support#100]
Describe request: Could you please add www.manager-magazin.de (Germany) to the extension?

Link of paywalled article: https://www.manager-magazin.de/unternehmen/burda-die-mutter-von-xing-cyberport-und-bunte-steckt-in-der-krise-wie-geht-es-weiter-a-0a87ffca-686c-42a9-867b-af64d0faa8fd

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): All of the mentioned. Doesn't work.

Browser (main version): Firefox 127.0.1

BPC-extension version (number): v3.7.1.0

Many thanks!

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix). PS site was just removed (first see changelog)`
