### ISSUE TITLE
No longer works for asia.nikkei.com

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#102]
Describe issue/request: 

Request for https://asia.nikkei.com/Politics/International-relations/Malaysia-and-Thailand-keen-to-join-BRICS-5-things-to-know

Link of paywalled article: 

https://asia.nikkei.com/Politics/International-relations/Malaysia-and-Thailand-keen-to-join-BRICS-5-things-to-know

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Failed.

Browser (main version): 
Edge

BPC-extension version (number): 
3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Was already fixed in release v3.7.2.0: first see changelog.

**Comment by optlee** [comment]
It seems 3.7.2 not work again...
"BPC > failed to load from Google webcache:"

url: https://asia.nikkei.com/Business/Technology/Amazon-to-launch-Temu-style-bargain-corner-for-Chinese-sellers

**Comment by optlee** [comment]
> > It seems 3.7.2 not work again... "BPC > failed to load from Google webcache:"
> 
> Always provide url of paywalled article.

https://asia.nikkei.com/Business/Technology/Amazon-to-launch-Temu-style-bargain-corner-for-Chinese-sellers

**Comment by bpc-clone** [comment]
Specific article works fine for me, but there are issues with new articles.\
Wait and see if it gets better (or site will be removed from add-on).
