### ISSUE TITLE
Request wn.de

### ISSUE THREAD

**Issue by Cub312** [bpc-clone/bpc_firefox_support#105]
Describe request: Request support for german site wn.de

Link of paywalled article: e.g. [https://www.wn.de/muenster/stadtteile/hiltrup/autobraende-ueberwachungskameras-diskussion-3016007?pid=true](url)

Actions you tried yourself and if it works (
1. clear cookies: didn't work, 
2. disable Javascript didn't work, 
3. change user-agent/referer not tried
4. reader view, didn't work, 
5. archive sites and/or didn't work,  (all site archives)
6. add a custom site): tried that with the actions described above

Browser (main version): Firefox 115.12.0esr

BPC-extension version (number): 3.7.2.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Indeed, site/group is no longer supported (no need to request unless you also provide a working fix).

**Comment by Cub312** [comment]
> Indeed, site/group is no longer supported (no need to request unless you also provide a working fix).

Ahh okay. Thought it maybe was removed by mistake or due to the new repo. 
So you don't have any idea on how to bring a Support for this site back?
Do you have any recommended approach or instruction on how to try this for myself?
There are many options to configure in bpc...
Thank you very much!
