### ISSUE TITLE
Request mittelbayerische.de (Germany)

### ISSUE THREAD

**Issue by hebabla** [bpc-clone/bpc_firefox_support#107]
Describe request: Request support for german site mittelbayerische.de

Link of paywalled article: [https://www.mittelbayerische.de/lokales/stadt-amberg-und-landkreis-amberg-sulzbach/wanderung-im-uebungsplatz-hohenfels-liess-eintauchen-in-natur-und-geschichte-16182138](url)

Actions you tried yourself and if it works:

1. clear cookies: didn't work,
2. disable Javascript didn't work,
3. change user-agent/referer didn't work
4. reader view didn't work,
5. archive sites didn't work, (all site archives)
6. add a custom site: tried that with the actions described above

Browser (main version): Firefox 127.0.2 (64-bit)

BPC-extension version (number): 3.7.2.0 

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix). PS site was just removed (first see changelog)`
