### ISSUE TITLE
Half pages for economist world-in-brief

### ISSUE THREAD

**Issue by Eclipse0023** [bpc-clone/bpc_firefox_support#11]
Describe issue/request: Show part of not the whole page

Link of paywalled article: https://www.economist.com/the-world-in-brief

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): reader view, clear cookies

Browser (main version): Firefox latest version

BPC-extension version (number): 3.6.6

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Page fixed in next release (for now use Google webcache).
