### ISSUE TITLE
Request ikz-online.de

### ISSUE THREAD

**Issue by hanzoh** [bpc-clone/bpc_firefox_support#112]
Describe issue/request: Please add ikz-online.de to group Funke Mediengruppe, it is working the same as wr.de etc

Link of paywalled article: https://www.ikz-online.de/lokales/hemer/article406716704/stadtwerke-hemer-was-sich-durch-enervie-einstieg-aendert.html
And the corresponding working archive.is link: https://archive.is/JOPVi

**Comment by bpc-clone** [comment]
Site re-added in latest master (or next release).
