### ISSUE TITLE
Request finance.si

### ISSUE THREAD

**Issue by schweigermatevz** [bpc-clone/bpc_firefox_support#114]
Describe issue/request: Request support for site finance.si

Link of paywalled article: 
https://www.finance.si/nepremicnine-cene-na-hrvaskem-rastejo-hitreje-kot-v-sloveniji-a-ne-povsod/a/9025303?src=A1

Actions you tried yourself:

- clear cookies
- disable Javascript 
- reader view
- archive sites
- add a custom site

Browser (main version): Version 127.0.1 (64-bit)

BPC-extension version (number): Bypass Paywalls Clean v3.7.3.0

**Comment by bpc-clone** [comment]
Site only supported as custom site (import from online): ads link to Google Search Tool (elaborate fix).
