### ISSUE TITLE
Request Le Dauphine - ledauphine.com

### ISSUE THREAD

**Issue by irenee44** [bpc-clone/bpc_firefox_support#116]
Describe issue/request: No access to ledauphine.com

Link of paywalled article: https://www.ledauphine.com/faits-divers-justice/2024/07/07/elle-veut-empecher-l-entree-de-sa-fille-dans-une-communaute-religieuse-elle-a-ete-endoctrinee-sans-que-je-m-en-apercoive

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): disable/enable UBlock origin

Browser (main version): Firefox 115.12.0esr (64 bits)

BPC-extension version (number): 3.7.3.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
