### ISSUE TITLE
Bug [Themarker.com]

### ISSUE THREAD

**Issue by bereld** [bpc-clone/bpc_firefox_support#117]
Describe issue/request: 
On the site themarker.com, paywall pages are loaded correctly, but after a short time (few minutes) they refresh and show an error message - Error 503 Service Unavailable. 
Disable all js seems to solve this, but then the site doesn't function correctly. Maybe there's a workaround?

Link of paywalled article: 
https://www.themarker.com/dynamo/cars/2024-07-04/ty-article/.premium/00000190-7d69-d0b6-a9b1-7dfdec230000

Actions you tried yourself and if it works: 
* clear cookies - didn't work.
* disable javascript - worked but created other problems - some parts not loading on main site page.

Browser (main version): 
Firefox 127.0.2 (64-bit)

BPC-extension version (number): 
v3.7.3.0

**Comment by bpc-clone** [comment]
Indeed, a known issue caused by bot-fix, but no fix besides disabling javascript.
