### ISSUE TITLE
WaPo comments not showing (dev: mobile only)

### ISSUE THREAD

**Issue by ishy001** [bpc-clone/bpc_firefox_support#126]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request:  Washington Post comments not showing using Firefox Nightly on Android

Link of paywalled article:  www.washingtonpost.com

Actions you tried yourself (mandatory) and if it works (clear cookies, disabe javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Running latest BPC version, cleared browser history/cookies

Browser (main version): Firefox Nightly 130.0a1

BPC-extension version (number): 3.7.5.0

**Comment by bpc-clone** [comment]
Indeed on mobile the comments open in a new page like `https://www.washingtonpost.com/comments?storyUrl=`, but this is collatoral damage of blocking the paywall-script (no fix).\
You can switch to desktop mode to watch the (inline) comments though.

Update: for mobile alternative link added to comments.
