### ISSUE TITLE
Request - 24heures.ch

### ISSUE THREAD

**Issue by P1tape** [bpc-clone/bpc_firefox_support#129]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
24heures.ch

Link of paywalled article: 
https://www.24heures.ch/elections-donald-trump-s-inquiete-du-retrait-de-joe-biden-298744570199

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
clear cookies, disable javascript, change user-agent/referer, reader view

Browser (main version): 
Firefox 128.0.1

BPC-extension version (number): 
3.7.6.0

**Comment by bpc-clone** [comment]
Site only has elaborate Google Search Tools fix as custom site (opt-in to custom sites & import custom sites).
