### ISSUE TITLE
Request/bug gamekult.com

### ISSUE THREAD

**Issue by P1tape** [bpc-clone/bpc_firefox_support#130]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
https://www.gamekult.com

Link of paywalled article: 
https://www.gamekult.com/jeux/granblue-fantasy-project-re-link-3050756691/test.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
clear cookies, disable javascript, change user-agent/referer, reader view

Browser (main version): 
Firefox 128.0.1
BPC-extension version (number): 
3.7.6.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
