### ISSUE TITLE
Request for thewirechina.com

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#131]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
https://www.thewirechina.com/2024/07/21/chinas-tech-turnaround-crackdown-investments-ai-government/

Link of paywalled article: 
https://www.thewirechina.com/2024/07/21/chinas-tech-turnaround-crackdown-investments-ai-government/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Didn't work

Browser (main version): 
Chrome

BPC-extension version (number): V3.7.2.6

**Comment by bpc-clone** [comment]
Only supported (in next release) when you opt-in to custom sites (and have Leaky Paywall).\
PS for now you can also add the domain as custom site (only set title and domain).
