### ISSUE TITLE
No longer seems to work for diepresse.com

### ISSUE THREAD

**Issue by em345** [bpc-clone/bpc_firefox_support#133]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: diepresse.com doesn't seem to work

Link of paywalled article: https://www.diepresse.com/5416223/wer-traut-sich-endlich-auch-karl-marx-vom-sockel-zu-stossen

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Firefox (newest version)

BPC-extension version (number): 3.7.6.0

**Comment by bpc-clone** [comment]
No fix (full article no longer in source code): site will be removed.
