### ISSUE TITLE
Request tanea.gr

### ISSUE THREAD

**Issue by Thomas888-alt** [bpc-clone/bpc_firefox_support#135]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Encountered a paywall

Link of paywalled article: https://www.tanea.gr/print/2024/07/29/sports/t16pisti-kai-oxi-apogoiteyst16i/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried all the above 

Browser (main version): firefox latest  128.0.3

BPC-extension version (number): 3.7.6.0

**Comment by Thomas888-alt** [comment]
Unfortunately for me does not show up .
I am using the cnrl+ u !
Am i doing something wrong?
I am novice in that stuff.
Thanks for the response!!!

**Comment by Thomas888-alt** [comment]
I found it somehow in the page source. I hope we can get a permanent fix in the add-on.
Keep up the great work!!!

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS page source also only contains partial text.
