### ISSUE TITLE
Request nnn.de

### ISSUE THREAD

**Issue by mahehro** [bpc-clone/bpc_firefox_support#14]
Describe issue/request: Is the same as svz.de

Link of paywalled article: 

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 

BPC-extension version (number): 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site is already in custom sites (import from online).\
PS actually use the issue template.
