### ISSUE TITLE
Request/bug [thebell.io]

### ISSUE THREAD

**Issue by stanokk** [bpc-clone/bpc_firefox_support#140]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: BPC doesn't work on thebell.io

Link of paywalled article: https://thebell.io/chto-stoit-za-bumom-elitnoy-nedvizhimosti-protesty-v-venesuele-i-voprosy-k-avtovozhdeniyu-tesla

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, add a custom site

Browser (main version): iceraven-2.18.2 (Build #2016016922), 9c50d2933+
GV: 125.0.2-20240419144423
AS: 125.0.1

BPC-extension version (number): Bypass Paywalls Clean v3.7.7.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
