### ISSUE TITLE
latercera.com no longer works

### ISSUE THREAD

**Issue by steban3** [bpc-clone/bpc_firefox_support#141]
hello friend! 
Thanks for all your work!

I'm having trouble with latercera.com, the site modified their paywall so now i can't access to the news, can you please check if there's any fix?

Thanks again!

Link of paywalled article: https://www.latercera.com/nacional/noticia/los-angustiantes-minutos-que-vivieron-los-efectivos-que-llegaron-a-socorrer-a-los-carabineros-asesinados-en-canete/XH3KAMEVSRABLLCNB62LCTWVSE/

I tried clearing cookies, disabling javascript, change user-agent/referer, archive sites and added as a new custom site but nothing worked 

Browser (main version): FIREFOX 128.0.3 (64-bit)

BPC-extension version (number):  v3.7.7.0

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

For now you can also add this filter to your adblocker:\
latercera.com##div.pw-frontier:remove()

**Comment by steban3** [comment]
Ohhh thanks! It did work after i added the filter. And you we're right, the content it's all there.

Thanks again dude
