### ISSUE TITLE
Request news.abplive.com

### ISSUE THREAD

**Issue by github-gitlab** [bpc-clone/bpc_firefox_support#142]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request:
news.abplive.com

Link of paywalled article:
https://news.abplive.com/india-at-2047/demand-indian-defence-items-growing-philippines-envoy-josel-f-ignacio-abpp-1707041

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):
clear cookies, disable javascript, change user-agent/referer, reader view

Browser (main version):
115.13.0esr (64-bit)

BPC-extension version (number):
3.7.7.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
