### ISSUE TITLE
cn.wsj.com no longer works

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#147]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
Can't bypass

Link of paywalled article: 

https://cn.wsj.com/amp/articles/%E4%B8%AD%E5%9B%BD%E9%A6%96%E4%BE%8B%E5%8D%95%E8%BA%AB%E5%A5%B3%E6%80%A7%E5%86%BB%E5%8D%B5%E6%A1%88%E4%BA%8C%E5%AE%A1%E4%BB%8D%E5%88%A4%E5%8E%9F%E5%91%8A%E8%B4%A5%E8%AF%89-42af6762

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome

BPC-extension version (number): 3.7.8.3

**Comment by bpc-clone** [comment]
No fix for cn subdomain: support will be removed from add-on.

**Comment by ipfans** [comment]
You can read the English version of the article for now, it's a bit annoying but at least it's usable
