### ISSUE TITLE
Request algonquinbeyond.com

### ISSUE THREAD

**Issue by benjistern** [bpc-clone/bpc_firefox_support#149]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Tried to add custom but was unable to succeed.

Link of paywalled article:  https://algonquinbeyond.com/campsites/head-lake-campsite-1/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried all.

Browser (main version): Firefox 129.0

BPC-extension version (number): 3.7.8.0

**Comment by bpc-clone** [comment]
Domain added to custom sites (import from online & opt-in to custom sites)
