### ISSUE TITLE
ksta.de & rundschau-online.de no longer working

### ISSUE THREAD

**Issue by bierle-cnj** [bpc-clone/bpc_firefox_support#151]
Describe issue/request:  Ksta.de and rundschau-online.de  (same publisher) stopped working shortly after the last fix for them. Publisher adopted to it.

Link of paywalled article (example): https://www.rundschau-online.de/koeln/stadt-koeln-einfuehrung-von-kuenstlicher-intelligenz-ki-moeglich-844004 

Browser (main version): Firefox 129.0

BPC-extension version (number): 3.7.9.0

**Comment by bierle-cnj** [comment]
Forgot to add: I highly appreciate your work and effort!

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).\
PS next time if site `stopped working shortly after the last fix` also report it shortly after.

**Comment by bierle-cnj** [comment]
Sorry, my bad. Forgot about it, because I was on holiday
