### ISSUE TITLE
Request kathimerini.gr

### ISSUE THREAD

**Issue by mvlassis** [bpc-clone/bpc_firefox_support#152]
Describe issue/request: Add support for the following domain of a popular Greek media outlet:
- www.kathimerini.gr

Link of paywalled article: https://www.kathimerini.gr/opinion/563169559/kalokairi-toy-erimiti-i-ton-idonon/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable JavaScript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
- Reader View works
- Disabling JavaScript using ublock origin works
- Adding the domain as a custom site works
- The article doesn't exist in archive.is
- Copying and pasting the code to https://codebeautify.org/htmlviewer works

Browser (main version): Mozilla Firefox 129.0.1

BPC-extension version (number): v3.7.9.0

**Comment by bpc-clone** [comment]
Site uses general paywall-script of piano.io (enable block in options): just remove cookies (& grant host permission for domain) once by BPC icon.\
No additional settings needed.
