### ISSUE TITLE
Request studio.glassnode.com

### ISSUE THREAD

**Issue by moizhaiderr** [bpc-clone/bpc_firefox_support#153]
Request for this new site related to crypto analysis.
website name is glassnode studio.
url is studio.glassnode.com.
Want to unlock each and every section of it to be unlocked if possible much appreciated.
I also tried other sites over extension opt in custom sites but didnt get to it.
wanna learn and know each every step details and further insight how to add custom sites whats protocol and main things to follow and keep in mind to bypass it overall paywall and sign in popup.

In last thank u so much for this great work u r doing God work much appreciated kudos.
tried to contact u over X also.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
Images are just blurred, but seem to be fake.

Not all sites have a custom fix though (for instruction see issue template & readme).\
PS no support on X.
