### ISSUE TITLE
Request levelup.gitconnected.com (dev: medium)

### ISSUE THREAD

**Issue by pickfire** [bpc-clone/bpc_firefox_support#154]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: medium site

Link of paywalled article: https://levelup.gitconnected.com/adding-a-retry-mechanism-to-functions-in-rust-3bfd958180f8

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): https://freedium.cfd/adding-a-retry-mechanism-to-functions-in-rust-3bfd958180f8

Browser (main version): firefox 129.0

BPC-extension version (number): 3.7.9.0

**Comment by bpc-clone** [comment]
For custom Medium domains opt-in to custom sites (extension adds links to external sites with full content).\
Main domain of this site isn't a Medium site though (fixed in next release).
