### ISSUE TITLE
record.pt &  cmjornal.pt not working

### ISSUE THREAD

**Issue by zecavalo** [bpc-clone/bpc_firefox_support#156]
Describe issue/request: Record.pt not working ; cmjornal.pt not working

Link of paywalled article: https://www.record.pt/futebol/futebol-nacional/liga-betclic/fc-porto/detalhe/todos-os-pormenores-do-negocio-evanilson-margem-alargada-no-bonus-de-10-m

Also: https://www.cmjornal.pt/famosos/detalhe/luis-montenegro-as-primeiras-ferias-como-governante

They are both from the same media group.

Cleaned cache and cookies, tried read mode

Browser (main version): Firefox 129 on Linux and also on Android

BPC-extension version (number): v3.7.9.0

**Comment by bpc-clone** [comment]
Site already fixed in latest master (or next release): `Always first see changelog`
