### ISSUE TITLE
Haaretz group sites not working anymore

### ISSUE THREAD

**Issue by BoredGeo** [bpc-clone/bpc_firefox_support#159]
Describe issue/request:  Getting Error 403 Forbidden for all Haaretz links. 

Link of paywalled article: https://www.haaretz.co.il/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): When I changed the user agent to firefox 127 the site did load. Clearing cookies didn't help, neither did disabling JS.

Browser (main version): Firefox 129.01

BPC-extension version (number): v3.7.9.0

**Comment by hundreAd100** [comment]
same
user-agent "Mozilla/5.0 (Java) outbrain" no longer works

**Comment by shlomo68** [comment]
same for me

**Comment by r-whitlock** [comment]
same issue as all above

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
If update rules doesn't fix the issue: disable group in options & open article with archive.today (see BPC icon).

**Comment by BoredGeo** [comment]
Thank you!

**Comment by Nirsch1** [comment]
There's still a problem - There's a horizontal overflow when reading the articles from a cellphone.
i.e. one needs to move the page from left to right and vice versa, in order to read the entire page.

**Comment by bpc-clone** [comment]
For cosmetic issues use the link to archive.is
