### ISSUE TITLE
.xpi file being served with improper mime type

### ISSUE THREAD

**Issue by celenityy** [bpc-clone/bpc_firefox_support#162]
Hi there,

When going to the download URL of BPC (`https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi`), rather than trying to install the add-on, it appears to simply download it as a .xpi file. This appears to be due to the file's mime type not being served as `application/x-xpinstall`.

This makes installing the extension more difficult for users, but also creates issues for those who use enterprise policies, making them unable to allow users to install your extension.

Can anything be done to fix this? 

Very much appreciated, thank you. 

PS. Please consider moving the source code to somewhere like [Codeberg](https://codeberg.org/) instead of GitFlic. Using a Russian-only website like this puts a massive barrier to entry, and will reduce the amount of people willing & able to contribute. I myself tried creating an account to file this issue over there instead, but was simply unable to due to the language barrier. (Even using translations... I was still unable to create an account). You could also mirror to both if desired as well.

I think it might also eventually be worth hosting your own [Gitea instance](https://about.gitea.com/), that way you can avoid being taken down entirely.

**Comment by bpc-clone** [comment]
Well, first of all don't blame the DMCA 'victim' ;-)

Indeed, but GitFlic issue (probably caused by type of links they use).\
They also don't allow xpi-uploads to the releases though (zip-files get some weird link with hash filename) though.\
No issues on GitFlic (yet), but no problem for me to create an account.

Codeberg is suggested a lot as alternative, but also subject to German paywall circumvention laws.

No intent to host repo (with Gitea) on a (virtual) private server.

**Comment by celenityy** [comment]
> Well, first of all don't blame the DMCA 'victim';-)

Wasn't trying to blame you my friend, apologies if it came off that way! Thank you for your amazing work on this extension, you are doing everyone a service. It is very much appreciated, and I respect you for continuing your work in spite of the DMCAs and setbacks you face.

> Indeed, but GitFlic issue (probably caused by type of links they use).

Ok, understood. Will investigate other options then.

> Codeberg is suggested a lot as alternative, but also subject to German paywall cicumvention laws.\

Ah, I was not aware of that. Makes sense then, I respect your decision.
