### ISSUE TITLE
Request: rbc.ru & investing.com

### ISSUE THREAD

**Issue by bratishka-mishka** [bpc-clone/bpc_firefox_support#168]
Describe issue/request: 
All articles are still closed / paywalled for reading on websites (look at the printscreens): https://pro.rbc.ru/ and https://ru.investing.com/news/pro

Link of paywalled article: 
1. https://pro.rbc.ru/
2. https://ru.investing.com/news/pro

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
I tried to do different settings during adding this articles to the common list of the media but nothing changed - articles are still closed as if I didn't use your program but it's on. At the same time another sites from default list is opened to me. Please tell me what settings need to be made so that the closed articles of these media can be read.

Browser (main version): Firefox 115.14.0esr (64-разрядный) (the latest version)

BPC-extension version (number): BPC v3.7.9.0
![Снимок экрана 2024-08-26 в 0 53 32](https://github.com/user-attachments/assets/9f75f2dc-a51b-42ac-89ea-2b16c04a54e2)
![Снимок экрана 2024-08-26 в 0 54 10](https://github.com/user-attachments/assets/ed2b37ff-dd7c-4456-8fbf-7d6063ccb65b)

**Comment by bpc-clone** [comment]
Indeed sites aren't supported.\
Sites have hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
