### ISSUE TITLE
Bypass for New Criterion?

### ISSUE THREAD

**Issue by Apollonius1199** [bpc-clone/bpc_firefox_support#17]
Is there a bypass for the New Criterion?

(Btw, I sent a DM on X regarding this, but was unable to reply to your DM)

Article link: https://newcriterion.com/article/the-arc-of-empire/

Actions tried: Archive.fo did not work, clearing cookies did not work, switching browsers did not work, Google cache did not work, reader view did not work

Browser (main version): Brave 1.65 and Orion 1.38 on iOS

BPC-extension version (number): BPC 3.6.1.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site already added in latest master/update rules (or next release).\
PS you have to update manually.
