### ISSUE TITLE
Request brazilian.report

### ISSUE THREAD

**Issue by goliv04053** [bpc-clone/bpc_firefox_support#171]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Paywall

Link of paywalled article: https://brazilian.report/power/2024/08/30/supreme-court-x-ban-brazil/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Clear cookies didn't worked, disabling javascript don't work, reader view don't work,

Browser (main version): Firefox 129.0.2

BPC-extension version (number): 3.8.1.1

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
