### ISSUE TITLE
Request: formula1.com

### ISSUE THREAD

**Issue by githubtefo** [bpc-clone/bpc_firefox_support#175]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: remove registration paywall

Link of paywalled article: https://www.formula1.com/en/latest/article/the-strategist-how-sainz-helped-leclerc-beat-mclaren-and-the-odds-to-seal-a.3xUwv6CFe6scAkxi9VLaIY

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): firefox for android 129

BPC-extension version (number): 3.7.9.0

**Comment by bpc-clone** [comment]
Site has hard regwall (no fix), it seems.\
PS always first try do-it-yourself options.
