### ISSUE TITLE
Request ewmagazine.nl

### ISSUE THREAD

**Issue by dingo35** [bpc-clone/bpc_firefox_support#177]
Describe issue/request: 
ewmagazine.nl shows popup that prevents reading.

Link of paywalled article: 
https://www.ewmagazine.nl/nederland/opinie/2024/09/conservatismekloof-valt-reuze-mee-81035w/

Tried enabling/disabling javscript, uBlock origin: no success.

Browser (main version): 
Firefox

BPC-extension version (number): 
3.8.2.1

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
