### ISSUE TITLE
Request: themorningcontext.com

### ISSUE THREAD

**Issue by sam619007** [bpc-clone/bpc_firefox_support#178]
Describe issue/request: Can't get past the paywall

Link of paywalled article: https://themorningcontext.com/business/should-anyone-take-zees-subhash-chandra-seriously

Actions I tried and none of it worked: cleared cookies, disabled javascript, tried to archive site, used the add custom site in BPC options 

Browser (main version): Firefox 130.0 (64-bit)

BPC-extension version (number): 3.8.2.1

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
