### ISSUE TITLE
Stuttgarter-zeitung.de no longer working

### ISSUE THREAD

**Issue by bhe69** [bpc-clone/bpc_firefox_support#180]
Describe issue/request: Paywall on pages of Medienholding Süd (stuttgarter zeitung/nachrichten) is improperly removed: The overlay is no longer visible, but only the first "preview" paragraph is visible. Even worse: On non-paywalled articles only the first paragraph is visible.

Link of paywalled article:
https://www.stuttgarter-zeitung.de/inhalt.staatsgalerie-stuttgart-schliesst-2028-den-stirlingbau-kunstgebaeude-wird-zur-staatsgalerie.a20ff595-9692-49a1-be0f-57f53fb8c11c.html

https://www.stuttgarter-nachrichten.de/inhalt.umwege-am-hauptbahnhof-stuttgart-werbekunde-nimmt-bahn-in-stuttgart-auf-die-schippe.611af0d2-2cf9-4941-9eca-591e61052858.html

Browser (main version): 115.15.0esr 

BPC-extension version (number): 3.8.2.1

Thanks for the great addon!

**Comment by bpc-clone** [comment]
Site has hard paywall now (no fix), it seems: site will be removed.\
PS free articles have a regwall/metered paywall though (regwall-script)?

Update: not working listed, but still for unlisted sites (opt-in to custom sites) ...\
Let me know if in the future the site will be supported by archive.is
