### ISSUE TITLE
freiepresse.de no longer working

### ISSUE THREAD

**Issue by Chebulex** [bpc-clone/bpc_firefox_support#181]
Describe issue/request: 
freiepresse.de domain is not showing the unpaywalled version of the article. Instead the banner for buying the premium service is shown as usual

Example Link of paywalled article: https://www.freiepresse.de/chemnitz/30-grad-in-chemnitz-ist-das-normal-fuer-september-artikel13516753

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
* disable ad block
* clear cookies
* archive sites tried
* tried Chrome + plugin as well (same result)

Browser (main version): Firefox 130.0

BPC-extension version (number): v3.8.1.6

**Comment by bpc-clone** [comment]
Full content no longer available on Google webcache: site will be removed.
