### ISSUE TITLE
Request: gasworld.com

### ISSUE THREAD

**Issue by HBelger** [bpc-clone/bpc_firefox_support#183]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: cannot get behind subscription paywall (have followed all instructions, all opt-ins enabled)

Link of paywalled article: https://www.gasworld.com/story/kornbluth-helium-market-in-a-new-phase/2143947.article/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear web cache, clear cookies & permissions, disable ublock origin, remove/re-add to list of custom sites

Browser (main version): Firefox 130.0 (64-bit)

BPC-extension version (number): v3.8.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
