### ISSUE TITLE
nw.de no longer working

### ISSUE THREAD

**Issue by kawock727** [bpc-clone/bpc_firefox_support#191]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
Neue Westfaelische (nw.de) no longer working, I already updated bpc to the latest version from 3.5.6.0 to 3.8.3.0

Link of paywalled article: 
[https://www.nw.de/lokal/kreis_minden_luebbecke/bad_oeynhausen/23940726_Wegen-Attests-Patientin-aus-Bad-Oeynhausen-verpruegelt-ihren-Hausarzt-v1.html]

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Cleared cookies, updated bpc, updated bpc adblock filter

Browser (main version): Firefox 130.0

BPC-extension version (number): 3.8.3.0

Thank You very much

**Comment by bpc-clone** [comment]
Site already fixed in latest master (or next release): `Always first see changelog`\
PS or also use BPC filter + German userscript.
