### ISSUE TITLE
nouvelobs.com no longer working

### ISSUE THREAD

**Issue by Educatedjoker** [bpc-clone/bpc_firefox_support#194]
Describe issue/request: Cannot have the full article

Link of paywalled article: https://www.nouvelobs.com/o/20240914.OBS93578/topless-sur-la-plage-on-m-a-regardee-comme-un-objet-de-curiosite-et-ca-n-augure-rien-de-bon.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): None of the aforementioned actions worked, sadly

Browser (main version): Mozilla Firefox 130.0

BPC-extension version (number):  v3.8.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems: site will be removed.\
PS full content still available on Google Search Tool (only as custom site)
