### ISSUE TITLE
rugbyrama.fr (aka Midi Olympique) is no longer working

### ISSUE THREAD

**Issue by Educatedjoker** [bpc-clone/bpc_firefox_support#196]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: The extension doesn't seem to work on the articles of the website anymore

Link of paywalled article: https://www.rugbyrama.fr/2024/09/14/top-14-la-confirmation-apres-la-communion-pour-clermont-face-au-racing-12192754.php

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): None worked on my side.

Browser (main version): Firefox 130.0

BPC-extension version (number): v3.8.3.0

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).
