### ISSUE TITLE
Request monde-diplomatique.fr

### ISSUE THREAD

**Issue by Educatedjoker** [bpc-clone/bpc_firefox_support#199]
Describe request: Adding Le Monde Diplomatique

Link of paywalled article: https://www.monde-diplomatique.fr/2024/09/HALIMI/67466

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried everything but the custom site part

Browser (main version): Firefox 130.0

BPC-extension version (number): v3.8.3.0

Also, do you still have the list of sites for which there is no fix? I can't find it anymore.

Cheers!

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
