### ISSUE TITLE
Request [dn.se]

### ISSUE THREAD

**Issue by suatcamillo** [bpc-clone/bpc_firefox_support#201]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe request: Just wanna read news articles in dn.se

Link of paywalled article: https://www.dn.se/ekonomi/sa-stor-loneokning-skulle-du-haft-for-att-matcha-prisokningarna/

Actions you tried yourself (mandatory) and if it works: I tried clearing cookies, disabling javascript, reader view, an a few archive sites. Tried the custom site thing as well but couldn't make it work. I don't know if it is my incompetence or not, though. 😅

Browser (main version): Firefox 130.0.1

BPC-extension version (number): v3.8.4.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`\
PS full content available by Google Search Tool (see BPC icon/popup) though (elaborate 'fix').
