### ISSUE TITLE
Request: leprogres.fr

### ISSUE THREAD

**Issue by Moingt42** [bpc-clone/bpc_firefox_support#204]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Unable to read article from leprogres.fr

Link of paywalled article: https://www.leprogres.fr/societe/2024/09/25/une-nouvelle-formation-apprendre-la-langue-des-signes

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, reader view, archive sites 

Browser (main version): Firefox 130.0.1

BPC-extension version (number): 3.8.5.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
