### ISSUE TITLE
Request hbrfrance.fr

### ISSUE THREAD

**Issue by Educatedjoker** [bpc-clone/bpc_firefox_support#208]
Describe request: Would it be possible to add the French version of HBR?

Link of paywalled article: https://www.hbrfrance.fr/strategie/comment-depasser-le-dogme-de-la-croissance-des-entreprises-60750

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable javascript, reader view and archive sites

Browser (main version): 130.0.1

BPC-extension version (number): v3.8.5.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
