### ISSUE TITLE
Request wyborcza.pl

### ISSUE THREAD

**Issue by takeda** [bpc-clone/bpc_firefox_support#209]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe request: Would be possible to add bypass for wyborcza.pl

Link of paywalled article: example: https://wyborcza.pl/TylkoZdrowie/7,137474,31317362,szkoly-katolickie-bojkotuja-akcje-szczepien-na-hpv-w-szkolach.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

I didn't see any change with clearing cookies, disabling javascript, changing user agent to google/twitter/facebook bot, reader view get rid of the fading at the end but it still wasn't the whole article.

I used archivebuttons.org and in it RemovePaywall.com worked: https://www.removepaywall.com/search?url=https://wyborcza.pl/TylkoZdrowie/7,137474,31317362,szkoly-katolickie-bojkotuja-akcje-szczepien-na-hpv-w-szkolach.html

Browser (main version): Firefox 130.0.1

BPC-extension version (number): 3.7.9.0

**Comment by bpc-clone** [comment]
Site was already added (in v3.8.3.0): `first see changelog` and update.

**Comment by takeda** [comment]
Thanks, I thought the extension was updating itself, but I guess it were just the rules.
