### ISSUE TITLE
Request iex.nl

### ISSUE THREAD

**Issue by ArieKindicator** [bpc-clone/bpc_firefox_support#217]
Describe issue/request: site shows a popup that prevents reading.

Link of paywalled article:  https://www.iex.nl/Premium/Adviezen/805411/Twijfel-over-houdbaarheid-beursrally-China-slaat-toe.aspx

Actions tried: to add a custom site with: clear cookies, disable javascript, change user-agent/referer. Also tried: archive.is, Google Search Tool. 

Browser (main version): Firefox

BPC-extension version (number): 3.8.6.1

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
