### ISSUE TITLE
Request nahverkehrhamburg.de

### ISSUE THREAD

**Issue by LinusKromnow** [bpc-clone/bpc_firefox_support#219]
Describe issue/request: site shows a popup that prevents reading, as well as ending early if popup is disabled.

Link of paywalled article:  https://www.nahverkehrhamburg.de/laengere-zuege-auf-der-u3-werden-noch-viele-jahre-brauchen-so-ist-der-planungsstand-204348/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): disabling javascript works somewhat, but you still can't see the full article, as it ends with a ... in the middle of a sentence.

Browser (main version):  Firefox

BPC-extension version (number): v3.8.6.1

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
