### ISSUE TITLE
Request: geopoliticalfutures.com

### ISSUE THREAD

**Issue by furlane** [bpc-clone/bpc_firefox_support#223]
Describe issue/request:  
New site request for --> geopoliticalfutures.com

Link of paywalled article: 
Some example articles --> 
https://geopoliticalfutures.com/the-future-of-drone-warfare/
https://geopoliticalfutures.com/daily-memo-germanys-economic-forecast-hungarys-russian-gas-imports/
https://geopoliticalfutures.com/the-world-in-2024/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Tried all actions below but none worked --> 
    Open incognito window and search for article in Google search (or webcache).
    Clear cookies for the site (by this add-on: opt-in to custom sites or grant host permission for the site; also enables blocking of general paywall scripts).
    Disable Javascript on the site (by browser, uBlock Origin or other add-on).
    Add the domain as custom site for more bypass options.
    Open page in reader view (by browser or add-on).
    Try one of the archive sites.

Browser (main version): 
Firefox, v131.0

BPC-extension version (number): 
v3.8.7.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
