### ISSUE TITLE
Request for vedomosti.ru

### ISSUE THREAD

**Issue by farag2** [bpc-clone/bpc_firefox_support#225]
Describe request: 
New site request for --> https://www.vedomosti.ru

Link of paywalled article: https://www.vedomosti.ru/technology/articles/2023/03/17/966905-u-bilaina-uskorilsya-ottok-abonentov

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): `all`

Browser (main version): Firefox 131.0.2

BPC-extension version (number): 3.8.7.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
