### ISSUE TITLE
Deleting old versions from `gitflic` breaks packaging

### ISSUE THREAD

**Issue by waltmck** [bpc-clone/bpc_firefox_support#232]
`bypass-paywalls-clean` is packaged with Nix as part of [this project](https://gitlab.com/rycee/nur-expressions). Nix requires fully declarative/reproducible builds, so a hash and download link must be specified in order to reproducibly download the same version. I recently [packaged version 3.8.4.0](https://gitlab.com/rycee/nur-expressions/-/merge_requests/73) to work with gitflic, but your recent commit broke my packaging since the expected file `bypass_paywalls_clean-3.8.4.0.xpi` was deleted from the `gitflic` repo.

I need a static link to an xpi file that won't be deleted by future updates. Ideally I would use a download link that specifies both the file and the commit hash, but I don't speak Russian and can't figure out how to do that in Gitflic. Is this possible?

Thanks.

**Comment by bpc-clone** [comment]
You can use this link for latest release (hash changes with version): https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi

**Comment by waltmck** [comment]
`bypass_paywalls_clean-latest.xpi` (as well as its hash) changes with each release, as you mention. This breaks reproducibility, so it is not possible to reconcile with the Nix package manager's guarantee of fully reproducible builds.

Since I'm not still not sure how to get a specific version, I think that this issue should be reopened. If you do not plan to support this, then it should be closed as not planned rather than as completed.

**Comment by bpc-clone** [comment]
No archive of old releases, but always the latest and the previous release on GitFlic (so available for around two weeks).

**Comment by ghost** [comment]
This is how I have it working on my config, and I haven't encountered a commit file not being found yet:

```
{ pkgs, ... }: let
  bpc = {
    commit = "634a41681d9e2df036177f0577039bcf58cb4a68";
    sha256 = "sha256-DLhryk7rdglguLEUscvZgveC2adyTDTyC0mp2eTuvBs=";
    version = "3.9.0.0";
  };
  firefox-addons = pkgs.nur.repos.rycee.firefox-addons;
in {
  home-manager.users.user.programs.firefox.profiles.user.extensions = with firefox-addons; let
    bpc-pkg = bypass-paywalls-clean.override {
      version = "${bpc.version}";
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-${bpc.version}.xpi&inline=false&commit=${bpc.commit}";
      sha256 = "${bpc.sha256}";
    };
  in [ bpc-pkg ];
}
```

**Comment by waltmck** [comment]
@JaysFreaky I'm not sure if this still works for you, but I am getting a 404 when I go to
```
https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-3.9.0.0.xpi&inline=false&commit=634a41681d9e2df036177f0577039bcf58cb4a68
```

**Comment by waltmck** [comment]
@JaysFreaky A more permanent workaround would be to develop a script which scans the `gitflic` for new updates and automatically updates the link/hash, but this doesn't solve the issue of lack of reproducibility for old version. I also don't have time to work on such a script (the annoying part is parsing the nonstandard format of `release-hashes.txt` to find the newest version), but if you manage to get something working Robert [generously offered to integrate it into the CI pipeline](https://gitlab.com/rycee/nur-expressions/-/merge_requests/74#note_2163422133) and I would be happy to help get it upstreamed.
