### ISSUE TITLE
Request for euractiv.com

### ISSUE THREAD

**Issue by teiraaa** [bpc-clone/bpc_firefox_support#233]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Article body does not show at all, it only shows a pop-up

Link of paywalled article: https://www.euractiv.com/section/economy-jobs/news/parliament-could-block-next-eu-budget-over-rrf-transparency-says-senior-mep/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):
* Cleared cookies
* Disabled JavaScript with uBlock Origin
* Opened on Reader View on Firefox (it just shows a bogus lorem ipsum text)
* Uploaded on archive.ph, it remains unchanged

Browser (main version): Firefox, v131.0.3 (64-bit)

BPC-extension version (number): v3.8.7.0

**Comment by bpc-clone** [comment]
No more fix: site was removed (see changelog).
