### ISSUE TITLE
Request for ole.com.ar

### ISSUE THREAD

**Issue by cristianer** [bpc-clone/bpc_firefox_support#234]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: After visiting some articles it shows me [this](https://imgur.com/a/YKwhdvP) sign in full window. This site is owned by clarin.com.

Link of paywalled article: https://www.ole.com.ar/futbol-internacional/eliminatorias/argentina-bolivia-hora-juega-ver-vivo-tv-online-formaciones-eliminatorias-sudamericanas_0_vnuHMQRVAb.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

- clear cookies, works.
- disable javascript, does not work, it says _you need to have javascript enabled to see this site._
- change user agent, does not work.
- reader view, it doesn't have one.
- custom site, didn't try

Browser (main version): Firefox 131.0.3

BPC-extension version (number): v3.8.7.0  

Thanks.

**Comment by bpc-clone** [comment]
First try to add this filter to your adblocker:\
`||clarin.com/*/zonda-*.js$script`

Update: site fixed in latest master/update rules (or next release).

**Comment by cristianer** [comment]
> First try to add this filter to your adblocker: `||clarin.com/*/zonda-*.js$script`

Yes, that works! Thanks.
