### ISSUE TITLE
Kompas.id not working for certain url

### ISSUE THREAD

**Issue by moreyball** [bpc-clone/bpc_firefox_support#241]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: for links that starts with kompas.id/artikel , it loads completely for a few seconds, but paywall appears after that

Link of paywalled article:  https://www.kompas.id/artikel/mengulik-mutu-tembakau-rokok-ilegal

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable javascript, archive.ph

Browser (main version): firefox 132.0b7 

BPC-extension version (number): 3.8.8.0

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
