### ISSUE TITLE
Request abendzeitung-muenchen.de

### ISSUE THREAD

**Issue by shelloverride** [bpc-clone/bpc_firefox_support#243]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
This site has paywalled articles which would be great to be able to read.

Link of paywalled article: 
https://www.abendzeitung-muenchen.de/politik/gebeutelte-bayern-spd-ein-bisschen-klassenkampf-muss-sein-art-1013648

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Cookie clearing didn't work,  Reader View didn't work, Archive.vn also didn't have it. Google Referer didn't do it.

Browser (main version): 
Firefox 132

BPC-extension version (number): 
3.8.8.0

**Comment by bpc-clone** [comment]
Only supported as custom site (import & opt-in to custom sites).
