### ISSUE TITLE
Request chinaglobalsouth.com

### ISSUE THREAD

**Issue by 2youn9** [bpc-clone/bpc_firefox_support#244]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: not working on this website. A test link: https://chinaglobalsouth.com/2024/10/19/taiwan-blames-china-for-s-africas-order-to-move-liaison-office/ 

Link of paywalled article: A test link: https://chinaglobalsouth.com/2024/10/19/taiwan-blames-china-for-s-africas-order-to-move-liaison-office/ 

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): yes, though not sure did it the right way.

Browser (main version): Firefox 131

BPC-extension version (number): v. 3.8.8.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS always mention which options you tried yourself.
