### ISSUE TITLE
MIT Sloan is no longer working.

### ISSUE THREAD

**Issue by Coxis** [bpc-clone/bpc_firefox_support#245]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
MIT Sloan paywall bypass is no longer working. I've used it in the past with no issues.

Link of paywalled article: 
https://sloanreview.mit.edu/article/changing-culture-is-central-to-changing-business-models/
https://sloanreview.mit.edu/article/to-cut-costs-know-your-customer/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  Clearing cookies via addon pop up, removing and re-adding site permissions, opened the link in archive page, pressed F9 for basic text view.

Browser (main version): 
Firefox 131.0.3 (aarch64)

BPC-extension version (number): 
3.8.8.0

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
PS timing issue specific to Firefox, it seems (until next release: sometimes manual refresh of page required).
