### ISSUE TITLE
Request [money.udn.com]

### ISSUE THREAD

**Issue by qazwsqa69** [bpc-clone/bpc_firefox_support#246]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe request: I would like to pass the paywall.

Link of paywalled article: https://money.udn.com/money/story/5604/8315333?from=edn_china_index

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  I have tried clear permissions, incognito browser, disable javascript by using ublock, changed user-agent, reader view and customised domain. Yet nothing worked:(

Browser (main version): Brave

BPC-extension version (number): 3.8.8.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
