### ISSUE TITLE
Request [theafricareport.com]

### ISSUE THREAD

**Issue by yosefahab** [bpc-clone/bpc_firefox_support#247]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 

Link of paywalled article: https://www.theafricareport.com/366113/kenya-on-track-for-imf-funding-as-central-bank-governor-highlights-economic-resilience/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Cleared cookies, disabled Javascript, tried reader view, custom site and archive site. None works.

Browser (main version): Firefox 131.0.3 on Ubuntu

BPC-extension version (number): 3.8.9.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`\
PS likewise for other requested sites (also first search issues).
