### ISSUE TITLE
Request: Puck News (puck.news)

### ISSUE THREAD

**Issue by Mennaruuk** [bpc-clone/bpc_firefox_support#25]
Describe issue/request: 

Link of paywalled article: https://puck.news/nicole-in-wonderland

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referrer, reader view, archive sites and/or add a custom site): Reader Mode, 1ft.io, 12ft.io, archive.today

Browser (main version): 125.0.3

BPC-extension version (number): 3.6.7.1 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

Screenshot:

![Screenshot 2024-05-09 at 15-20-15 Nicole in Wonderland](https://github.com/bpc-clone/bypass-paywalls-firefox-clean/assets/52135169/0ba64815-e8c5-4d0d-8bd9-4c8142ede3b1)

**Comment by bpc-clone** [comment]
No fix: `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).`

**Comment by newsjunkie247** [comment]
Right now the text for at least this Puck article is visible in the source test: https://puck.news/newsletter_content/nbcs-sir-charles-fantasies-paramount-buzz-beast-belt-tightening/ I don't know if that's temporary thing though.

**Comment by bpc-clone** [comment]
> Right now the text for at least this Puck article is visible in the source test: [puck.news/newsletter_content/nbcs-sir-charles-fantasies-paramount-buzz-beast-belt-tightening](https://puck.news/newsletter_content/nbcs-sir-charles-fantasies-paramount-buzz-beast-belt-tightening/) I don't know if that's temporary thing though.

Only newsletters are visible in reader view.
