### ISSUE TITLE
Request/bug [medwatch.com]

### ISSUE THREAD

**Issue by pmcarrion** [bpc-clone/bpc_firefox_support#255]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Add support for MedWatch

Link of paywalled article: https://medwatch.com/News/hearing_health/article17581109.ece

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): None of these options worked. I was able to read it using Google Search Tool.

Browser (main version): Firefox

BPC-extension version (number): 3.9.0.0

**Comment by bpc-clone** [comment]
No alternative fix, but Media Watch group added as custom (flex) site (in next release): custom sites > import (from online) & opt-in to custom sites.
