### ISSUE TITLE
Request: thetablet.org

### ISSUE THREAD

**Issue by forthwith247** [bpc-clone/bpc_firefox_support#257]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 

Link of paywalled article: https://thetablet.org/from-marvelous-mrs-maisel-to-blue-bloods-diocese-churches-being-featured-in-movies-and-television/?gated=true

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Reader View works, cookies/archive sites/Google-user agent does not work

Browser (main version): Firefox

BPC-extension version (number): latest Firefox version

**Comment by bpc-clone** [comment]
First try to add these 2 filters to your adblocker (and report back):\
`||thetablet.org$inline-script`
`thetablet.org##+js(rc, gated-content, body.gated-content)`

Update: domain also added to custom sites.

**Comment by forthwith247** [comment]
Yes, that seems to work. Thank you.
