### ISSUE TITLE
Request: Jacobin.com

### ISSUE THREAD

**Issue by Apollonius1199** [bpc-clone/bpc_firefox_support#26]
Bypass for Jacobin.com?

Link of paywalled article: https://jacobin.com/2024/04/socialists-in-the-kingdom-of-god

Clearing cookies failed, archive.vn failed, reader view failed, Google cache failed, was unable to register web account without paid subscription.

Browser (main version): Orion 1.3.8

BPC-extension version (number): BPC 3.6.7.1

**Comment by bpc-clone** [comment]
No fix: `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).`
