### ISSUE TITLE
Request/bug zugerzeitung.ch

### ISSUE THREAD

**Issue by alexanderadam** [bpc-clone/bpc_firefox_support#260]
Describe issue/request: 

interesting on this website is, that you see the article for a short moment and you'll also find the text in the DOM within the `script` tag (search for `content: { text: "Viele Verschuldete leben nach der «Vogel-Strauss-Taktik»: Sie stecken den Kopf in den Sand`…).

Link of paywalled article: 

- https://www.zugerzeitung.ch/zentralschweiz/zug/schulden-massiv-mehr-verschuldete-im-kanton-zug-es-ist-ein-teufelskreis-das-sind-die-gruende-ld.2582415

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): disabling JavaScript works

Browser (main version): FF 132.0.2

BPC-extension version (number): Bypass Paywalls Clean v3.6.3.0

**Comment by bpc-clone** [comment]
Site already supported as CH Media domain: request host permission for unlisted domain (by clearing cookies once by BPC-icon).
