### ISSUE TITLE
Request/bug ntnews.com.au

### ISSUE THREAD

**Issue by Tomotron2k** [bpc-clone/bpc_firefox_support#262]
Describe issue/request: **Could you please add the Northern Territory News?**

Link of paywalled article: **https://www.ntnews.com.au/truecrimeaustralia/police-courts-nt/new-pilatus-pc12-ngx-planes-join-nt-police-force-fleet/news-story/11171402ff63e50c3154a48cbb29a5cf**

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **Yes to all**

Browser (main version): **Mozilla Firefox**

BPC-extension version (number): **3.9.2.0**

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`

**Comment by enifrog** [comment]
Hi there, I am also wanting to use NTnews.com.au

As far as I can tell, it is using the same JSON and paywall tactics that the rest of the Australian News Corp websites are using as they are all owned by the same company. If heraldsun.com.au and dailytelegraph.com.au (etc) are working using BPC, then I'd assume NTnews could use the same fix.

Could you please look into this again?
Thanks

**Comment by bpc-clone** [comment]
No fix = no fix, but full content available when you copy the url to Google Search/Inspection Tool: https://search.google.com/test/rich-results

Update: GST-link added to subscribe-page in next release (when you request host permission for domain).

**Comment by enifrog** [comment]
> No fix = no fix, but full content available when you copy the url to Google Search/Inspection Tool: https://search.google.com/test/rich-results
> 
> Update: GST-link added to subscribe-page in next release (when you request host permission for domain).

No worries, thanks :)
