### ISSUE TITLE
Request/bug gamefile.news

### ISSUE THREAD

**Issue by Unit076** [bpc-clone/bpc_firefox_support#263]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Hard paywall. Removing cookies, reader view, disabling Js, adding it to custom site, and archive don't work. 404 show up when using BeautifyHTML.

Link of paywalled article: https://www.gamefile.news/p/xbox-phil-spencer-blizzard-avowed-south-of-midnight

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Firefox 132.0.2 (64-bit)

BPC-extension version (number): 3.9.2.0

**Comment by bpc-clone** [comment]
Site (Substack-blog) has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
