### ISSUE TITLE
tt.com no longer working

### ISSUE THREAD

**Issue by Sodeepinside** [bpc-clone/bpc_firefox_support#266]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
**The Site loads everything but it looks like it cuts the text in 0,5 seconds and puts it back behind the paywall**

Link of paywalled article: 
https://www.tt.com/artikel/30896027/schreckgespenst-donald-trump-wie-handelskonflikte-tirols-wirtschaft-schaden
https://www.tt.com/artikel/30896029/oesv-star-liensberger-bei-98-weltcupsieg-von-shiffrin-in-levi-starke-zweite

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
**clear cookies and permission.**

Browser (main version): **Firefox**

BPC-extension version (number): **v3.9.2.0**

**Comment by bpc-clone** [comment]
Site (Firefox timing-issue) fixed in latest master (or next release).
