### ISSUE TITLE
Request: risk.net

### ISSUE THREAD

**Issue by paolo993788** [bpc-clone/bpc_firefox_support#267]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
Hi guys, meanwhile thanks for what you do, I wanted to kindly ask if it would be possible to add this site “risk.net” as well. Thanks in advance

Link of paywalled article: https://www.risk.net/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 

BPC-extension version (number):

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
PS use full issue template.
