### ISSUE TITLE
Request: rhein-zeitung.de

### ISSUE THREAD

**Issue by moep-de** [bpc-clone/bpc_firefox_support#269]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
After website update the addon (BPC-clone) is not working anymore

Link of paywalled article: 
https://www.rhein-zeitung.de/ (all pwaywall articles)

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Disable Javascript, reader view and archive sites not working.

Browser (main version): 
Firefox 132.0.2

BPC-extension version (number): 
3.9.2.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
PS site was removed in latest release (first see changelog).
