### ISSUE TITLE
Spiegel.de: no article content found!

### ISSUE THREAD

**Issue by OrkoGrayskull** [bpc-clone/bpc_firefox_support#27]
Describe issue/request: The following message appears when you call up a Spiegel+ article: 

> BPC > Try for full article text [...] | no article content found! | : | archive.today | archive.ph

Normally the article is downloaded from archive.* and displayed below the red BPC text. This no longer seems to work.

Link of paywalled article: Every Spiegel+ article

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Deleted browser cache, updated BPC, nothing helped

Browser (main version): Firefox 124.2.0

BPC-extension version (number): v3.6.7.1

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
