### ISSUE TITLE
Request: perspectivemedia.com

### ISSUE THREAD

**Issue by goliv04053** [bpc-clone/bpc_firefox_support#271]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
paywall after three articles
Link of paywalled article: 
https://www.perspectivemedia.com/starmer-to-meet-with-chinese-president-xi-jinping-at-g20-summit/
Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Cleaning cookies reset the counter, disabling javascript kinda works but logo gets larger
Browser (main version): 
Zen Browser 1.0.1-a.19 (Firefox 132.0.1)
BPC-extension version (number): 
v3.9.2.0

**Comment by bpc-clone** [comment]
First try adding these filters to your adblocker:
`||perspectivemedia.com/wp-admin/admin-ajax.php$xmlhttprequest,~third-party`
`perspectivemedia.com##div.hustle-ui`
