### ISSUE TITLE
Request finanz-szene.de

### ISSUE THREAD

**Issue by datarepos76** [bpc-clone/bpc_firefox_support#272]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request:  Adding site to default sites

Link of paywalled article: https://finanz-szene.de/banking/bei-der-aareal-bank-machen-die-pe-investoren-jetzt-halt-doch-pe-dinge/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all above

Browser (main version): Firefox 132.0.2

BPC-extension version (number): 3.9.2.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
