### ISSUE TITLE
Request/bug [thediplomat.com]

### ISSUE THREAD

**Issue by Apollonius1199** [bpc-clone/bpc_firefox_support#277]
Describe issue/request: Magazine articles for The Diplomat do not display past the paywall. 

Link of paywalled article: https://magazine.thediplomat.com/2024-11/southeast-asias-semiconductor-play

Clearing cookies and using archive site did not solve problem. 

Browser (main version): Orion 1.3.12

BPC-extension version (number): 3.9.2

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
PS full content also available with reader mode (add-on).
