### ISSUE TITLE
Request: pff.com

### ISSUE THREAD

**Issue by hugo9655** [bpc-clone/bpc_firefox_support#281]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: paywall for the rest of the article

Link of paywalled article: https://www.pff.com/news/fantasy-football-start-sit-advice-week-12-2024

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): cleared cookies, disabled js, added as custom site and changed user-agent (got blocked), reader view, archive site. none worked.

Browser (main version): Firefox 132.0.2

BPC-extension version (number): v3.9.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
