### ISSUE TITLE
Request theinitium.com

### ISSUE THREAD

**Issue by dzx-dzx** [bpc-clone/bpc_firefox_support#282]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: It's been observed that the content of articles on theinitium.com can be seen for a short period of time. A paywall is applied afterwards, similar to how NYT behaves.

Link of paywalled article: https://theinitium.com/article/20241126-mainland-young-people-night-time-cycling

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Block request for https://cdn1.wallkit.net/js/integration/latest/wallkit-integration-library.min.js?ver=3.3.8

Browser (main version): 

BPC-extension version (number): 3.9.4.0

**Comment by bpc-clone** [comment]
Indeed, they switched to Wallkit paywall.\
For now add this filter to your adblocker:\
||wallkit.net/js/$script,third-party

Update: 
Site added in latest master/update rules (or next release).
