### ISSUE TITLE
elperiodico.com Paywalled articles not fully loading

### ISSUE THREAD

**Issue by albertfc** [bpc-clone/bpc_firefox_support#283]
**Describe issue/request:** 
Not loading full article. 

**Link of paywalled article**: https://www.elperiodico.com/es/deportes/20241128/suerte-ancelotti-mbappe-florentino-entretenido-112122275

**Actions you tried yourself (mandatory) and if it works** 
- clear cookies: does not work
- disable javascript: IT WORKS
- archive sites and/or add a custom site): IT WORKS (e.g https://clearthis.page/?u=https://www.elperiodico.com/es/deportes/20241128/suerte-ancelotti-mbappe-florentino-entretenido-112122275)

**Browser** (main version): Firefox 133.0 (aarch64)

**BPC-extension version** (number): 3.9.4.0

**Comment by bpc-clone** [comment]
Site (timing-issue) fixed in latest master (or next release).\
For now add this filter to your adblocker: `elperiodico.com##+js(ra, class, div.ft-helper-closenews, stay)`
