### ISSUE TITLE
Request fix for clarin.com

### ISSUE THREAD

**Issue by cristianer** [bpc-clone/bpc_firefox_support#29]
Describe issue/request: In clarin.com every article with "Solo suscriptores" requires to log into an account.

Link of paywalled article: https://www.clarin.com/politica/pavas-doble-fondo-falsas-embarazadas-pendrives-escondidos-boca-carne-congelada-explosivo-informe-judicial-narcos-presos-hoy_0_0zgtceTGYJ.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Don't work (clear cookies), works (disabling Javascript and reader view before the site finish loading).

Browser (main version): Firefox 125.0.3 (64-bit)

BPC-extension version (number): BPC 3.6.7.1

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules only with v3.6.8.0 (or next release)
