### ISSUE TITLE
The Verge post content dissapears. 

### ISSUE THREAD

**Issue by SkateWarp** [bpc-clone/bpc_firefox_support#290]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: BPC breaks The Verge. Any link to a post, loads, but after a few seconds, the content of the post disappears. 

Link of paywalled article: 

Any post to the site, example: https://www.theverge.com/2024/12/3/24312198/microsoft-ftc-antitrust-invesigation-leak

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

I disabled BPC and the content of the post does not disappear (also added as a excluded site works too)

Browser (main version): 

Firefox 133.0

BPC-extension version (number): 

v3.7.8.0

Screenshot of the example link: 
![CvhHsej55Z](https://github.com/user-attachments/assets/7ee1124d-8c9b-448f-b409-1735a6bed7dd)

**Comment by SkateWarp** [comment]
Whoops, forgot the title. 😅

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
PS options > `Check for update rules at startup` or manually `Check updates sites`

**Comment by SkateWarp** [comment]
> Site fixed in latest master/update rules (or next release). PS options > `Check for update rules at startup` or manually `Check updates sites`

Thank you for the fast reply! 
Before posting the issue I also clicked `Check updates sites` and the behavior did not change.

**Comment by SkateWarp** [comment]
I had to update the plugin (downloading from gitflic) manually, and then clicking `Check updates sites` fixed it. The version I had (v3.7.8.0) did not do nothing, while the new version (v3.9.4.0), did the trick.
