### ISSUE TITLE
Bug wsj.com - comments not working

### ISSUE THREAD

**Issue by hub2git** [bpc-clone/bpc_firefox_support#294]
Describe issue/request:  Thanks to Bypass Paywalls, I can read articles on the Wall Street Journal. My problem is that I can't read the comments.

Link of paywalled article: https://www.wsj.com/finance/currencies/bitcoin-supply-limit-crypto-value-29e068b4?mod=lead_feature_below_a_pos3
 right now has 555 comments, based on the home page.
![Screenshot 2024-12-10 at 23-57-03 The Wall Street Journal - Breaking News Business Financial   Economic News World News and Video](https://github.com/user-attachments/assets/381457e5-9fd9-454b-a5cc-eaddd0191421)

Browser (main version): firefox 133.0

BPC-extension version (number):  3.9.6.0

**Comment by bpc-clone** [comment]
Not caused by BPC, but cookie-consent issue.\
Your adblocker probably blocks it (also for me): disable adblocker (once) & see `manage cookies` link in page footer.

**Comment by hub2git** [comment]
> Not caused by BPC, but cookie-consent issue. Your adblocker probably blocks it (also for me): disable adblocker (once) & see `manage cookies` link in page footer.

Hi there. I let the WSJ article load then disabled ublock origin for that site. But I don't see "manage cookies" link at the bottom of that article page.

Here's what I see:
![Screenshot 2024-12-11 at 18-40-17 Behind Bitcoin’s Rally Is a Simple Fact Supplies Are Limited - WSJ](https://github.com/user-attachments/assets/28c611f5-3088-4051-ab26-f40789158261)

**Comment by hub2git** [comment]
@bpc-clone any advice?

**Comment by bpc-clone** [comment]
Check Firefox security/privacy settings, but again not a BPC-issue.
