### ISSUE TITLE
Request boredpanda.com

### ISSUE THREAD

**Issue by ToddDTaft** [bpc-clone/bpc_firefox_support#296]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Some pages blocked partially through page

Link of paywalled article: https://www.boredpanda.com/being-an-adult-tweets/
Note: need to scroll down to #50 to see block.

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Open in private window, Activate NoScript plugin, reader view, look at page on archive.org and clearthis.page (archive.today didn't have page indexed and a request to archive page didn't complete in the time it took to write this issue) - none worked; however, when I view source of the page, I can see item#51 and beyond, so I would expect it to be possible to make a rule, since the server appears to send the data for parts of the page not rendered by the browser.

Browser (main version): Firefox 133.0.3

BPC-extension version (number): 3.9.6.0

**Comment by bpc-clone** [comment]
Not really a news site, but try to add these filters to your adblocker:\
`boredpanda.com##+js(rc, open-list-items, div.open-list-items)`
`boredpanda.com##div#show-all-images-block-premium`
