### ISSUE TITLE
Request Kicker.de

### ISSUE THREAD

**Issue by vmeyerm** [bpc-clone/bpc_firefox_support#298]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: www.kicker.de

Link of paywalled article: https://www.kicker.de/hoch-und-weit-ist-vergangenheit-der-neue-stil-der-2-liga-1074326/artikel

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all of them

Browser (main version): 133.0.3

BPC-extension version (number): 3.9.6.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
