### ISSUE TITLE
Request [thestar.com.my]

### ISSUE THREAD

**Issue by superbarney** [bpc-clone/bpc_firefox_support#307]
Describe issue/request: 
Support thestar.com.my (paywalled after about opening 5-10 articles)

Link of paywalled article: 
https://www.thestar.com.my/news/nation/2024/12/24/e-hailing-driver-charged-with-murdering-nurul-asikin
https://www.thestar.com.my/news/nation/2024/12/24/wan-junaidi-voices-support-over-sarawak-govt039s-decision-to-retain-assessment-exams
https://www.thestar.com.my/news/nation/2024/12/24/terengganu-cops-seize-244kg-of-meth-in-largest-drug-bust-worth-rm78mil
https://www.thestar.com.my/business/business-news/2024/12/24/china039s-yuan-nears-13-month-low-amid-falling-bond-yields
https://www.thestar.com.my/aseanplus/aseanplus-news/2024/12/16/10-years-jail-for-singapore-man-who-posed-as-forex-trader-cheated-13-people-of-over-us34mil
https://www.thestar.com.my/aseanplus/aseanplus-news/2024/12/24/sacking-of-singposts-group-ceo-could-waylay-efforts-to-restructure-business-revive-growth-analysis
https://www.thestar.com.my/aseanplus/aseanplus-news/2024/12/24/four-million-elderly-in-thailand-to-get-10000-baht-handout-by-end-january

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Tried disabling javascript via uBlock Origin

Browser (main version): 
Firefox 133.0.3

BPC-extension version (number): 
3.9.6.4

**Comment by bpc-clone** [comment]
Metered paywall can be bypassed by clearing cookies (with add-on) or add the domain to custom sites (only enter title & domain).\
PS no fix for premium articles (with lock icon).
