### ISSUE TITLE
Request/ [heraldo.es]

### ISSUE THREAD

**Issue by osborne69** [bpc-clone/bpc_firefox_support#308]
Describe issue/request:
Not loading full article, only subscriptors

Link of paywalled article: https://www.heraldo.es/noticias/aragon/zaragoza/2024/12/23/compras-navidenas-ambiente-centro-zaragoza-somos-espanoles-todos-ultima-hora-1787740.html

Actions you tried yourself (mandatory) and if it works

    clear cookies: not work
    disable javascript: not work
    archive sites and/or add a custom site): 
https://clearthis.page/?u=https://www.heraldo.es/noticias/aragon/zaragoza/2024/12/23/compras-navidenas-ambiente-centro-zaragoza-somos-espanoles-todos-ultima-hora-1787740.html
Not work

Browser (main version): Firefox Nightly 135.0a1

BPC-extension version (number): 3.9.6.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS fix as custom site no longer works.
