### ISSUE TITLE
Request [note.com]

### ISSUE THREAD

**Issue by DerpyMario** [bpc-clone/bpc_firefox_support#310]
Describe issue/request:
Using latest version of firefox mobile extension Android

Link of paywalled article: 
https://note.com/p_rcl_zr/n/n84b0a3ca8799

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried using reader mode but it's only showing five scenes, normal mode only shows a half of scene 6 and then fades out to a paywall descryption saying: 

 ここから先は
 15,755字 / 20画像

¥ 500
ポイント
抽選でnoteポイント最大100%還元 〜1/9まで

From here on
15,755 characters / 20 images

¥500
point
Up to 100% note points will be returned by lottery until 1/9

Browser (main version): firefox

BPC-extension version (number): 
Bypass Paywalls Clean v3.9.6.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS don't copy-paste previous issue.
