### ISSUE TITLE
bug [limburger.nl]

### ISSUE THREAD

**Issue by Pentasis** [bpc-clone/bpc_firefox_support#313]
Describe issue/request: 
This domain no longer works.

Link of paywalled article: 
https://www.limburger.nl/regio/gulpen-wittem/mechelen/oud-wethouder-van-gulpen-wittem-marion-van-der-kleij-heeft-geen-spijt-van-vertrek-uit-de-politiek-ik-kon-er-niet-meer-van-slapen/29448279.html

I tried clearing cookies and disabling javascript, tried reading-view and looked for a version on archive.org.

Browser (main version): FF 133.0.3

BPC-extension version (number): 3.9.6.4

**Comment by bpc-clone** [comment]
No more archive-fix, but full content still available with Google Search Tool (see BPC icon/popup).
