### ISSUE TITLE
Request: falter.at

### ISSUE THREAD

**Issue by em345** [bpc-clone/bpc_firefox_support#34]
Describe issue/request: If possible, it would be awesome to include this site 

Link of paywalled article: https://www.falter.at/zeitung/20230607/im-namen-von-karl-marx

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I tried to use the settings in the example json list of custom sites; cleared the cookies, block javascript and use reader mode, set useragent to googlebot, block and allow cookies, but it still has fadeout,  paywall-wrapper.. archive.is doesn't work; 

Browser (main version): Firefox 126.0 on Android 14

BPC-extension version (number): Bypass Paywall Clean v3.6.8.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), but first `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
