### ISSUE TITLE
webcache bug Economist

### ISSUE THREAD

**Issue by Eclipse0023** [bpc-clone/bpc_firefox_support#35]
Describe issue/request: Economist China news shown BPC > failed to load from Google webcache: 
Link of paywalled article: https://www.economist.com/china/2024/05/14/the-xi-putin-partnership-is-not-a-marriage-of-convenience

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cleared cookie

Browser (main version): Firefox latest

BPC-extension version (number): 3.6.8.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Only no Google webcache for this arrticle?\
Full text still available at archive.is though.

PS I've added a link to archive.is for articles without a Google webcache entry in latest master (or next release).

**Comment by Eclipse0023** [comment]
Thanks! Many article under china section is showing the same error with partial page.
![2024-05-20_09-46-26](https://github.com/bpc-clone/bypass-paywalls-firefox-clean/assets/115081729/d929806e-a771-485f-9c2b-b5170b796d4f)
https://www.economist.com/china/2024/05/16/how-taiwan-still-hangs-on-to-property-in-bits-of-china
https://www.economist.com/china/2024/05/09/in-todays-china-to-get-rich-is-perilous
https://www.economist.com/china/2024/05/09/why-young-russian-women-appear-so-eager-to-marry-chinese-men
