### ISSUE TITLE
Request retail-week.com & thegrocer.co.uk (WilliamReed group)

### ISSUE THREAD

**Issue by N01N3** [bpc-clone/bpc_firefox_support#42]
Describe issue/request: Would like to request a few domains

Link of paywalled article: Two sites

https://www.retail-week.com/customer/retail-sales-drop-again-in-april/7046286.article
https://www.thegrocer.co.uk/finance/city-snapshot-wet-weather-dampens-uk-retail-sales/691709.article

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Have tried playing with the options, none seemed to work.

Browser (main version): Firefox

BPC-extension version (number): v3.6.8.0  

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
For both sites of group you can clear cookies to bypass paywall though (or add as custom site).

**Comment by gety9** [comment]
@bpc-clone could you please tell when new release will be out? (latest is still Apr 21)

Looking to it to make ft.com work. (related issue was deleted)
