### ISSUE TITLE
new request : usine-digitale.fr

### ISSUE THREAD

**Issue by Pozelj** [bpc-clone/bpc_firefox_support#43]
Describe issue/request: usine-digitale (also infopro digitale but does not work). Thanks.

Link of paywalled article: https://www.usine-digitale.fr/article/choose-france-faut-il-s-inquieter-des-investissements-massifs-des-fournisseurs-de-cloud-americains.N2213335

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): tried to add as a custom site

Browser (main version): firefox 126.0

BPC-extension version (number): 3.6.9.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), but first `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`

**Comment by Pozelj** [comment]
seems to be similar to "lemoniteur.fr" or "usinenouvelle.com". Is it possible for you to test ? Thanks
