### ISSUE TITLE
new request : cfnews.net

### ISSUE THREAD

**Issue by Pozelj** [bpc-clone/bpc_firefox_support#44]
Describe issue/request: paywall. Thanks.

Link of paywalled article: https://www.cfnews.net/L-actualite/M-A-Corporate/Operations/Acquisition/Deloitte-renforce-son-pole-sustainability-483877

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): tried custom site, google cache, disable javascript

Browser (main version): 126

BPC-extension version (number): 3.6.9.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has has hard paywall (no fix), it seems.
