### ISSUE TITLE
Request: sspai.com

### ISSUE THREAD

**Issue by komjourney** [bpc-clone/bpc_firefox_support#45]
Describe issue/request: Clearn paywall,Thanks

Link of paywalled article: https://sspai.com/post/81335
https://sspai.com/post/83162
                                        
Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Added to custom sites,but still not work,cleared the cookies, block javascript

Browser (main version): Firefox 126.0 

BPC-extension version (number): v3.6.9.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has has hard paywall (no fix), it seems.
