### ISSUE TITLE
Site Request: sciencenews.org

### ISSUE THREAD

**Issue by anotatta** [bpc-clone/bpc_firefox_support#46]
Please add www.sciencenews.org/

Link of paywalled article: 
https://www.sciencenews.org/article/largest-ape-extinct-earlier-than-thought

Thanks.

**Comment by bpc-clone** [comment]
Use issue template: clearing cookies removes paywall.\
PS site also added to latest master/update rules (or next release).

**Comment by anotatta** [comment]
Oh!  Thanks.
