### ISSUE TITLE
Request: Manorama Online

### ISSUE THREAD

**Issue by sillsytuffs** [bpc-clone/bpc_firefox_support#47]
Describe issue/request: Many articles are free to read, Premium Content is behind a PayWall

Link of paywalled article: https://www.manoramaonline.com/premium/sports/2024/05/27/sunil-narine-the-spin-wizard-and-kkrs-trump-card-in-ipl-2024.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I tried multiple combinations in Custom sites but I couldn't figure out the right combination to Bypass.

Browser (main version): Android FireFox 126 

BPC-extension version (number): 3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site added in latest master/update rules (or next release).

**Comment by sillsytuffs** [comment]
Thank you!
