### ISSUE TITLE
No longer works for sueddeutsche.de

### ISSUE THREAD

**Issue by ghost** [bpc-clone/bpc_firefox_support#48]
Describe issue/request: Süddeutsche zeitung doesnt seem to work anymore. 

Link of paywalled article: https://www.sueddeutsche.de/politik/emmanuel-macron-staatsbesuch-dresden-europa-1.7438496?reduced=true

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Firefox, newest version

BPC-extension version (number): 3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site (main domain) fixed in latest master (or next release).
