### ISSUE TITLE
Webcache bug economist podcasts 

### ISSUE THREAD

**Issue by moreyball** [bpc-clone/bpc_firefox_support#49]
Describe issue/request: BPC > failed to load from Google webcache. Requested url was not found in this server. 

Link of paywalled article: https://www.economist.com/podcasts/2024/05/15/why-the-defrosting-of-antarctica-will-be-felt-everywhere

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, reader view

Browser (main version): Firefox 126.0 

BPC-extension version (number): 3.7.0.0

**Comment by bpc-clone** [comment]
Try opening the article with archive.today, but it doesn't contain the podcast-link either.

**Comment by moreyball** [comment]
It seems like archive today doesn't archive the audio , even in regular articles:
https://www.economist.com/asia/2024/05/23/geopolitics-helps-reignite-new-caledonias-anti-colonial-unrest

The screenshot shows the audio bar but the webpage doesn't 
![Screenshot_2024-05-29-13-07-45-480_org.mozilla.firefox-edit.jpg](https://github.com/bpc-clone/bypass-paywalls-firefox-clean/assets/60646400/ce838117-439a-4ecc-8cd9-3a6da866c43d)



![Screenshot_2024-05-29-13-07-09-483_org.mozilla.firefox-edit.jpg](https://github.com/bpc-clone/bypass-paywalls-firefox-clean/assets/60646400/bf2d1c4c-58c6-4651-a22e-e3c97168b4ce)

So, I guess no fix?

**Comment by bpc-clone** [comment]
No more fix for podcasts+ (or any other audio files).
