### ISSUE TITLE
New Request: quizlet.com

### ISSUE THREAD

**Issue by celenityy** [bpc-clone/bpc_firefox_support#50]
Describe issue/request: **Definitions for terms don't appear after your first visit to the site unless you log-in/sign-up or pay.**

Link of paywalled content: **This applies for any set on Quizlet, [here](https://quizlet.com/902590982/television-y-peliculas-flash-cards/)'s a random example for testing purposes.**

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **I've confirmed blocking cookies for the site bypasses the paywall, and the definitions now appear as expected.**

Browser (main version): **Confirmed working on Firefox 126.0 & Brave 1.66.115.**

BPC-extension version (number): **v3.7.0.0 (Though the fix works without the BPC extension)**

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Interesting, but cookie-fix doesn't work for https://quizlet.com/explanations  
Still you can add the domain to custom sites though.
