### ISSUE TITLE
courrierinternational.com no longer working

### ISSUE THREAD

**Issue by garfieldairlines** [bpc-clone/bpc_firefox_support#53]
Describe issue/request: Paywall bypassing doesn't work anymore

Link of paywalled article: https://www.courrierinternational.com/article/presidentielle-au-mexique-l-heure-d-une-femme-au-pouvoir-a-sonne-mais-pas-celle-du-feminisme

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Mercury 123.0.1 (64 bits)

BPC-extension version (number): v3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Googlebot-fix no longer works, but for now use archive.today link (in BPC icon/popup).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).
