### ISSUE TITLE
Request [politiken.dk]

### ISSUE THREAD

**Issue by LoiDNguyen** [bpc-clone/bpc_firefox_support#56]
Describe request: Please add politiken.dk to the default sites  

Link of paywalled article: n/a

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Configure to add politiken.dk 
{"Politiken Denmark":{"domain":"politiken.dk","allow_cookies":1}}

Browser (main version):  Firefox 126.0.1 (64-bit)

BPC-extension version (number): 
New release v3.7.0.0Options | v3.6.9.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site was added to custom sites some time ago (import & opt-in to custom sites).\
To fix layout: see help > troubleshooting.
