### ISSUE TITLE
telerama.fr no longer working

### ISSUE THREAD

**Issue by Chrischris69** [bpc-clone/bpc_firefox_support#58]
Describe issue/request: Paywall bypassing doesn't work anymore

Link of paywalled article: https://www.telerama.fr/plateformes/pyramid-game-sur-paramount-un-thriller-coreen-sur-fond-de-harcelement-scolaire_cri-7032941.php

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Firefox 126.0.1 (Windows & Android)

BPC-extension version (number): v3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Googlebot-fix no longer works: only elaborate (custom) fix by opening article with 'Google Search Tool' (see BPC icon/popup) ...\
Readme: `for Google Search Tool test url & copy html (tab) code to https://codebeautify.org/htmlviewer`
