### ISSUE TITLE
Bug [Malayala Manorama]

### ISSUE THREAD

**Issue by sillsytuffs** [bpc-clone/bpc_firefox_support#59]
Describe issue/request: This site was added as a rule update in the previous version and it was working fine. But yesterday when my plugin was updated to the latest version 3.7.1.0, only the top portion of the article is displayed for both premium AND non-premium content. Rest of the article is not displayed 

Link of paywalled article: https://www.manoramaonline.com/premium/opinion-and-analysis/2024/06/02/market-experts-forecast-2150-per-cent-jump-in-stocks-amid-bjp-election-victory.amp.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cleared cache, cookies, enable/disable plugin, enable/disable site

Browser (main version): Android Firefox 126.
0.1
BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
PS next time just respond to initial issue.

**Comment by sillsytuffs** [comment]
Thank you!
