### ISSUE TITLE
Request to add qpbriefing.com

### ISSUE THREAD

**Issue by foxation** [bpc-clone/bpc_firefox_support#60]
Describe issue/request: Could you please add qpbriefing.com to your list of default sites?

Link of paywalled article: https://www.qpbriefing.com/news/fao-launches-investigation-into-government-s-serviceontario-staples-deal

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites

Browser (main version): Firefox 126 (64-bit)

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Domain added as custom site, but only working in next release (v3.7.3.0).
