### ISSUE TITLE
New request : h2-view.com

### ISSUE THREAD

**Issue by Pozelj** [bpc-clone/bpc_firefox_support#63]
Describe issue/request: h2-view.com. Thanks

Link of paywalled article: https://www.h2-view.com/feature/market-report-global-energy-perspective-2022/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): disable JS, google cache and reader view

Browser (main version): 126.0.1

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
