### ISSUE TITLE
thenewsminute.com no longer works

### ISSUE THREAD

**Issue by gaba512** [bpc-clone/bpc_firefox_support#64]
Describe issue/request: Unable to get passed paywall

Link of paywalled article: [www.thenewsminute.com](https://www.thenewsminute.com/powertrip/naidu-nitish-hold-the-key-how-india-bloc-is-wooing-them)

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disabe Javascript, archive sites

Browser (main version): Firefox 126.0.1

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by wolfdael** [comment]
This is a bug. It used to work previously. Example article not working -- https://www.thenewsminute.com/tamil-nadu/exclusive-kalakshetra-probe-recommends-police-cases-against-3-teachers

All articles in this link don't work - https://www.thenewsminute.com/premium

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
