### ISSUE TITLE
Request rnz.de

### ISSUE THREAD

**Issue by Meo-one** [bpc-clone/bpc_firefox_support#65]
Describe issue/request: 
PBC doesn't work on this site. The Paywall remains.

Link of paywalled article: 
rnz.de/region/rhein-neckar_artikel,-Hirschberg-Drogen-Automat-in-Leutershausen-sorgt-fuer-Aufregung-_arid,1349284.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
- block general paywall-scripts: they were already all blocked, all checkmarks were enabled
- create a custom site: the "ON" sign on the Addon button appears, but the Paywall remains still. (I don`t have an idea wich adjustments have to be seted)

Browser (main version): 
Firefox 126.0.1 

BPC-extension version (number): 
v3.7.1.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).
PS site was just removed (first see changelog).`
