### ISSUE TITLE
Firefox on Android migration?

### ISSUE THREAD

**Issue by bobpaul** [bpc-clone/bpc_firefox_support#66]
Is there any way to migrate an install that was sideloaded on Firefox on Android without downgrading to an old version of firefox beta again?

Following the instructions while the project was on gitlab, I installed a really old version of Firefox Beta for Android, sideloaded the XPI, and then upgraded and it's worked with all the caveats and did the automatic updates. But of course now it's no longer updating.

I assume the answer is no, but I thought I'd check.

**Comment by bpc-clone** [comment]
See new instruction in readme (only Android 10+).
