### ISSUE TITLE
bug asia.nikkei.com

### ISSUE THREAD

**Issue by Daymond** [bpc-clone/bpc_firefox_support#69]
Describe issue/request: couldn't read full article

Link of paywalled article: https://asia.nikkei.com/Business/China-tech/CATL-tops-China-s-corporate-subsidies-list-outranking-oil-majors

refresh several times, got no help.

Browser (main version): Firefox 127.0

BPC-extension version (number): 3.7.1.0

**Comment by bpc-clone** [comment]
Some Firefox-specific issue, but for now open article with Google webcache (BPC icon/popup).

PS site fixed in next release (for when Piano.io script/xhr is blocked by other add-on or Firefox enhanced tracking protection).
