### ISSUE TITLE
Request: ftchinese.com

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#71]
Describe issue/request: 

Please help to support http://ftchinese.com/

Link of paywalled article: 

http://ftchinese.com/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Not worked.

Browser (main version): 
Edge

BPC-extension version (number): 
V3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), but `first request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
