### ISSUE TITLE
Request aftenposten.no

### ISSUE THREAD

**Issue by forteller** [bpc-clone/bpc_firefox_support#72]
Describe issue/request: I would like to request that you add aftenposten.no, if possible.

The reason why this might be tricky is that they employ two different ways of paywalling their articles. One of them I think is impossible to get past, the other is very easy to get past. I don't know if it's possible for you to just fix the one that is easy to get past, but I think you should be able.

Link of paywalled article: 
Here are some of the ones that I think you should be able to get past (type 1):
https://www.aftenposten.no/verden/i/bm58Xd/solstorm-utloeste-spektakulaert-lysshow
https://www.aftenposten.no/verden/i/MnR3Mm/apple-knuser-instrumenter-og-lager-rabalder
https://www.aftenposten.no/norge/i/8qmJ2x/glisne-kontorlokaler-paa-inneklemt-fredag

Here are some of the ones I don't think you'll get past, but I'll add them here just in case (type 2):
https://www.aftenposten.no/verden/i/GyaA3Q/avsloeringene-har-sjokkert-danmark-og-er-et-etisk-minefelt-naa-kommer-spoersmaalene
https://www.aftenposten.no/meninger/leder/i/Ppywez/varsling-paa-ville-veier 

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): For the Type 1 paywall all you have to do to get past it is to use the uBlock zapper mode on the whole page/background twice. For Type 2 I can not think of any way to get past it.

Browser (main version): Firefox 126

BPC-extension version (number): 3.6.7.1

Thank you so much for your work!

**Comment by bpc-clone** [comment]
No fix for premium, but for free articles add this filter to your adblocker:\
||aftenposten.no/cnp-assets/vendors.*.js$script,~third-party

**Comment by forteller** [comment]
Thanks for the reply, but unfortunately that solution broke the first linked article.

Also, I don't understand why bypassing this login wall should not be a part of BPC?

**Comment by bpc-clone** [comment]
Use these filters instead:\
aftenposten.no##div.hyperion-css-1cc2qe9,div[class^="advertory-"]  
aftenposten.no##body:style(overflow: auto !important)

Which percentage of articles has a regwall though?\
Partial fix will be added to BPC adblocker filter.

PS full content of premium articles are available with Google Search Tool (elaborate 'fix').\
I may add it as a custom site later.
