### ISSUE TITLE
Request for lifeweek.com.cn

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#77]
Describe issue/request: 
Request for https://www.lifeweek.com.cn

Link of paywalled article: 

Request for https://www.lifeweek.com.cn/article/228250?origin=6

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 
Edge
BPC-extension version (number): 

3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
