### ISSUE TITLE
Request caixinglobal.com

### ISSUE THREAD

**Issue by XuecongLin** [bpc-clone/bpc_firefox_support#78]
Describe issue/request: 

https://www.caixinglobal.com/

Link of paywalled article: 

https://www.caixinglobal.com/2024-06-15/china-rolls-out-new-rules-for-online-sites-to-curb-cyberbullying-102206478.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Failed

Browser (main version): 

Edge

BPC-extension version (number): 

3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
