### ISSUE TITLE
Request for nikkei.com (member-only)

### ISSUE THREAD

**Issue by PathosEthosLogos** [bpc-clone/bpc_firefox_support#81]
Describe issue/request: Nikkei industrial news
Nikkei.com has some free articles by default, but there are sections where there are absolutely no free articles.

Link of paywalled article: any article from https://www.nikkei.com/topics/18083101

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): combination of googlebot and javascript disabling

Browser (main version): Firefox 127

BPC-extension version (number): v3.7.1.0 

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

Nikkei already exists, but it's Nikkei Asia *only*. It would be nice to have the original Japanese Nikkei bypassed for industrial news as well.

**Comment by bpc-clone** [comment]
Site hard paywall (no fix), it seems).
