### ISSUE TITLE
Request lemonde.fr

### ISSUE THREAD

**Issue by ibay1** [bpc-clone/bpc_firefox_support#86]
Describe issue/request: Can you add this website please

Link of paywalled article: https://www.lemonde.fr/politique/article/2024/06/19/a-louviers-les-gens-disent-le-rn-il-n-y-a-qu-eux-qu-on-n-a-pas-essayes_6241152_823448.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I have try everything but that's doesn't work!

Browser (main version): Firefox

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`. 
PS site was just removed (first see changelog).
