### ISSUE TITLE
The Washington Post: no full article

### ISSUE THREAD

**Issue by rogervdweyden** [bpc-clone/bpc_firefox_support#9]
Describe issue/request:
**For articles on The Washington Post, only the first few sentences are shown. The rest of the article is hidden.**

Link of paywalled articles:
https://www.washingtonpost.com/technology/2024/04/23/tiktok-ban-us-start-explained/
https://www.washingtonpost.com/technology/2024/04/29/tiktok-capcut-ban-impact/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):
**I cleared cookies & permissions. Google webcache worked. But Clearthis.page and 1ft.io did not work.**

Browser (main version):
**Firefox 125.0.2 (64-bit)**

BPC-extension version (number):
**v3.6.6.0**

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

PS `update rules`: options > `Check for update rules at startup`

**Comment by sesinger** [comment]
Problem is back again on May 1st. V3.6.6.0

**Comment by Viavi91** [comment]
> Problem is back again on May 1st. V3.6.6.0

This was fixed on the master.zip, not the current release - you will need to wait for next release.
