### ISSUE TITLE
Request [handelsblatt.com]

### ISSUE THREAD

**Issue by nilspstr** [bpc-clone/bpc_firefox_support#91]
Describe issue/request: could you please add handelsblatt.com to the bypass paywall

Link of paywalled article: https://www.handelsblatt.com/unternehmen/it-medien/sony-music-schwere-vorwuerfe-gegen-den-europachef-des-musik-konzerns/100046383.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  cleared cookies - doesnt work, disabled javascript - doesnt work 

Browser (main version): Firefox Version 127.0.1 (64 Bit)

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).
PS site was just removed (first see changelog).`

**Comment by Cub312** [comment]
@nilspstr get into your regional "Börsenverein", member of the BVH. You only have to pay a small fee (12€?) each semester and as a benefit, you get Handelsblatt premium.
