### ISSUE TITLE
Not working on hindutamil.in premium articles

### ISSUE THREAD

**Issue by Manikandan-Vanniyar** [bpc-clone/bpc_firefox_support#94]
Describe issue/request: 

Link of paywalled article: https://www.hindutamil.in/amp/news/supplements/penn-indru/1269170-faces-dear-dad.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): All of the mentioned

Browser (main version): Firefox Desktop with ublock origin

BPC-extension version (number): 3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
No fix, site will be removed.
