### ISSUE TITLE
Request [hs.fi]

### ISSUE THREAD

**Issue by LastRagnarokkr** [bpc-clone/bpc_firefox_support#95]
Describe request: 
Request to add hs.fi domain support

Link of paywalled article: 
https://www.hs.fi/taide/art-2000010495256.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
At time of request following has been tried without success.
- Cookies
- Javascript (NoScript)
- reader view
- archiving
- custom settings and bpc tools

User agent has not been tested.

Browser (main version): 
Version 127.0.1 (64-bit)

BPC-extension version (number): 
3.7.1.0

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix). PS site was just removed (first see changelog).`
