### ISSUE TITLE
nikkei asia not work

### ISSUE THREAD

**Issue by optlee** [bpc-clone/bpc_firefox_support#96]
Describe issue/request:  extension not worked on nikkei asia website

Link of paywalled article:  https://asia.nikkei.com/Business/Retail/Uniqlo-parent-to-digitally-track-materials-across-its-supply-chain

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Firefox 127.0.1

BPC-extension version (number): 3.7.1

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).
