### ISSUE TITLE
Request: businessinsider.de (Germany)

### ISSUE THREAD

**Issue by realResi** [bpc-clone/bpc_firefox_support#99]
Describe request: Could you please add www.businessinsider.de (Germany) to the extension?

Link of paywalled article: https://www.businessinsider.de/wirtschaft/zahnarzt-firma-zahneins-riskante-ops-fur-mehr-umsatz-durchgefuehrt/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): All of the mentioned. Doesn't work.

Browser (main version): Firefox 127.0.1

BPC-extension version (number): v3.7.1.0

Many thanks!

**Comment by bpc-clone** [comment]
Only elaborate Google Search Tool fix as custom site (custom sties > import from online & opt-in to custom sites).
